### PR TITLE
Updated the Download page to link to the new Marketplace Entry and generally reference the 4.0.0 version

### PR DESCRIPTION
**Pull request by keinhaar**

### CODE REVIEW

**Comment by keinhaar** [comment]
@niloc132 
Hi Colin, could you please check this PR, because the Documentation still references the old plugin.
Thanks

**Review by niloc132 — APPROVED** [review]
Thanks, I'll look into how to deploy this next.

**Comment by keinhaar** [comment]
@niloc132 
Hi Colin, i know you're busy and this is not the top priority, but it's now 8 month since this pull request. 
Is there any chance, that we can update the documentation? 
I would like to do more, if it ever gets online.

**Comment by niloc132** [comment]
Sorry, the deploy directions are quite frustrating - if you follow them, you break the site, the instructions only work if you built manually, copied extra files in, and then never run `clean`. As a result, there are stale files that should have been deleted before now...

I don't have a good way to consistently build, just I have a hacked up way to produce output that I'm not very confident in. I'm going to publish what should exist today, then merge this PR (and update the site) after we've made sure it seems to work?

**Comment by niloc132** [comment]
Done. I at least see that the updated date at the footer is set to today, and the nav stuff still seems to work - if you can take a quick pass and confirm things work, i'll land and deploy this PR.

**Comment by keinhaar** [comment]
Looks good to me. Nothing seems to have changed except the date.

Maybe we should rewrite the whole site without need for any maven build. Just uploading simple HTML, CSS, JS Files.
The contents will not change very frequently, so i see no benefits in having a complex build.

**Pull request merged**
